// src/app/layout.tsx
/*
 * Root Layout
 *
 * This is the root layout component for the application.
 * It handles global settings such as maintenance mode and includes
 * necessary providers and fonts for consistent styling across the app.
 */
import { Toaster } from "@/components/ui/sonner";
import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createClient } from "../lib/supabase/server";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data: settings } = await supabase
    .from("platform_settings")
    .select("maintenance_mode")
    .single();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  const isAdmin = user?.email === "krishna@bizorapro.com";

  if (settings?.maintenance_mode && !isAdmin) {
    return (
      <html>
        <body className="bg-black text-white flex items-center justify-center h-screen text-center p-4">
          <div>
            <h1 className="text-4xl font-bold text-primary mb-4">
              Under Maintenance 🛠️
            </h1>
            <p className="text-gray-400">
              BizoraPro is currently being upgraded. Please check back in 30
              minutes.
            </p>
          </div>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster position="top-center" richColors />
        <Analytics />
      </body>
    </html>
  );
}
